### ISSUE TITLE
Weird error message on Windows, when running the installer without administrator priviledges.

### ISSUE THREAD

**Issue by fmontesi** [jolie/release_tools#1]
@thesave : Think you can have a look at this, please? :-)

![image](https://cloud.githubusercontent.com/assets/2077129/12977303/3a72c966-d0ca-11e5-9607-2676bd624168.png)

**Comment by thesave** [comment]
Yep, I'll look into it in the week-end.

**Comment by thesave** [comment]
[This commit](https://github.com/jolie/release_tools/commit/1294ab58d344cd1d701a7d1b82fd5c6844ec3dc6) should fix the issue.

**Comment by mwallnoefer** [comment]
Looks reasonable, let us close this.
